# Generated by Django 5.1.4 on 2025-02-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planilla',
            old_name='verfificacion',
            new_name='verificacion',
        ),
    ]
