# Generated by Django 5.1.4 on 2025-02-18 12:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DASA', '0003_remove_empresa_art_remove_aspectoseguridad_planilla_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('CUIT', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Formato de CUIT incorrecto.', regex='[0-9]{11}$')])),
                ('razon_social', models.CharField(max_length=50)),
                ('rgrl', models.FileField(blank=True, null=True, upload_to='', verbose_name='RGRL')),
                ('venc_rgrl', models.DateField(blank=True, null=True, verbose_name='Vencimiento de RGRL')),
                ('rar', models.FileField(blank=True, null=True, upload_to='', verbose_name='RAR')),
                ('venc_rar', models.DateField(blank=True, null=True, verbose_name='Vencimiento de RAR')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='empresas', to='DASA.art', verbose_name='ART')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_calle', models.CharField(max_length=50)),
                ('dir_altura', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Solo se admiten números', regex='[0-9]+$')])),
                ('nro_de_obra', models.IntegerField()),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de obra')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin de obra')),
                ('estado', models.BooleanField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='DASA.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUIL', models.CharField(validators=[django.core.validators.RegexValidator(message='Formato de CUIL incorrecto.', regex='[0-9]{11}$')])),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nomina', to='DASA.obra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialRegulacionObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('regulacion', models.CharField(choices=[('MEDICION PAT', 'Medición PAT'), ('MEDICION PULSO', 'Medición pulso'), ('MEDICION ICUM', 'Medición ICUM'), ('ERGONOMIA', 'Ergonomía'), ('PLANO DE OBRA', 'Plano de obra'), ('PLANO DE EXCAVACIÓN', 'Plano de excavación'), ('PLANO DE DEMOLICIÓN', 'Plano de demolición')], max_length=20)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DASA.obra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialRegulacionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('regulacion', models.CharField(choices=[('MATAFUEGOS', 'Matafuegos'), ('CAPACITACION', 'Capacitación'), ('SIMULACRO', 'Simulacro'), ('EPP', 'Epp')], max_length=12)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DASA.obra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumentoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('tipo', models.CharField(choices=[('AVISO DE OBRA', 'Aviso de obra'), ('PROGRAMA', 'Programa de seguridad')], max_length=30)),
                ('doc', models.FileField(upload_to='documentos/', verbose_name='Documento')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DASA.obra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.PositiveIntegerField()),
                ('comentarios', models.TextField(max_length=500)),
                ('acciones', models.TextField(max_length=300, verbose_name='Acciones inmediatas')),
                ('verificacion', models.CharField(max_length=100, verbose_name='Verificación de las acciones tomadas')),
                ('fecha_efectiva', models.DateField()),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='DASA.obra')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='AspectoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ropa_trabajo', 'Uso de ropa de trabajo'), ('epp_basico', 'EPP básico'), ('epp_acorde', 'EPP acorde a los trabajos'), ('estado_conservacion', 'Estado y conservacion de los EPP'), ('Herramientas', 'Herramientas manuales'), ('Equipos', 'Equipos manuales'), ('Equipos_maquinas', 'Equipos y maquinas pesadas'), ('Electricidad', 'Tableros de electricidad'), ('Cables', 'Tendido de cables'), ('Excavaciones', 'Excavaciones'), ('Barandas', 'Barandas perimetrales'), ('Plataformas_trabajo', 'Platafromas de trabajo'), ('Botiquin', 'Botiquin'), ('COVID', 'Protocolo COVID-19'), ('andamios', 'Andamios'), ('escaleras', 'Escaleras'), ('arneses', 'Uso y estado de arneses'), ('Lineas_vida', 'Líneas de vida'), ('Oden_limpieza', 'Órden y limpieza'), ('Permiso_trabajo', 'Permiso de trabajo'), ('Pos_golpes', 'Posivilidad de golpes, caídas, resbalones, etc'), ('Izajes_manuales', 'Izajes manuales'), ('Izajes_equipos', 'Izajes por equipos'), ('Delimitacion', 'Delimitación de los trabajos'), ('Señalizacion', 'Señalización'), ('Otros', 'otros')], max_length=20)),
                ('cs', models.PositiveIntegerField(default=0)),
                ('ci', models.PositiveIntegerField(default=0)),
                ('na', models.BooleanField(default=False)),
                ('imagen', models.FileField(storage='/img/planillas', upload_to='')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspectos', to='DASA.planilla')),
            ],
        ),
        migrations.CreateModel(
            name='PresenteRegulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUIL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina_presente', to='DASA.nomina')),
                ('regulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DASA.historialregulacionnomina')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUIL', models.CharField(validators=[django.core.validators.RegexValidator(message='Formato de CUIL incorrecto.', regex='[0-9]{11}$')])),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('responsable_obra', models.BooleanField(verbose_name='Habilitado a ser responsable de obras')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planilla',
            name='hecha_por',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='DASA.responsableobra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='firma',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Firmas', to='DASA.responsableobra'),
        ),
    ]
