# Generated by Django 5.1.4 on 2025-02-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0005_alter_aspectoseguridad_tipo_alter_planilla_acciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='fecha_efectiva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
