# Generated by Django 5.1.4 on 2025-02-25 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0007_alter_planilla_hecha_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='hecha_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='DASA.responsableobra'),
        ),
    ]
