# Generated by Django 5.1.4 on 2025-02-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0008_alter_planilla_hecha_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectoseguridad',
            name='imagen',
            field=models.FileField(blank=True, null=True, storage='/img/planillas', upload_to=''),
        ),
    ]
