# Generated by Django 5.1.4 on 2025-02-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0009_alter_aspectoseguridad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
