# Generated by Django 5.1.4 on 2025-03-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0013_alter_empresa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
