# Generated by Django 5.1.4 on 2025-03-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0014_empresa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
