# Generated by Django 5.1.4 on 2025-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0017_alter_aspectoseguridad_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialdocumentoobra',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='historialdocumentoobra',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='historialregulacionnomina',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='historialregulacionnomina',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='historialregulacionobra',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='historialregulacionobra',
            name='fecha',
        ),
        migrations.AddField(
            model_name='historialdocumentoobra',
            name='fecha_carga',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historialdocumentoobra',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historialregulacionnomina',
            name='fecha_carga',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historialregulacionnomina',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historialregulacionobra',
            name='doc',
            field=models.FileField(null=True, upload_to='documentos/', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='historialregulacionobra',
            name='fecha_carga',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historialregulacionobra',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historialdocumentoobra',
            name='doc',
            field=models.FileField(null=True, upload_to='documentos/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='historialdocumentoobra',
            name='tipo',
            field=models.CharField(choices=[('AVISO_DE_OBRA', 'Aviso de obra'), ('PROGRAMA', 'Programa de seguridad')], max_length=30),
        ),
    ]
