# Generated by Django 5.1.4 on 2025-03-20 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0018_remove_historialdocumentoobra_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cel',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Solo números', regex='[0-9]$')]),
        ),
    ]
