# Generated by Django 5.1.4 on 2025-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0019_empresa_cel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='rar',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='RAR'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rgrl',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='RGRL'),
        ),
    ]
