# Generated by Django 5.1.4 on 2025-03-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0020_alter_empresa_rar_alter_empresa_rgrl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialdocumentoobra',
            name='tipo',
            field=models.CharField(choices=[('AVISO_DE_OBRA', 'Aviso de obra'), ('PROGRAMA', 'Programa de seguridad'), ('MEDICION PAT', 'Medición PAT'), ('MEDICION PULSO', 'Medición pulso'), ('MEDICION ICUM', 'Medición ICUM'), ('ERGONOMIA', 'Ergonomía'), ('PLANO DE OBRA', 'Plano de obra'), ('PLANO DE EXCAVACIÓN', 'Plano de excavación'), ('PLANO DE DEMOLICIÓN', 'Plano de demolición')], max_length=30),
        ),
        migrations.DeleteModel(
            name='HistorialRegulacionObra',
        ),
    ]
