# Generated by Django 5.1.4 on 2025-03-25 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0021_alter_historialdocumentoobra_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Obras', to='DASA.responsableobra'),
        ),
    ]
