# Generated by Django 5.1.4 on 2025-03-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0023_alter_obra_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsableobra',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='responsableobra',
            name='nombre',
        ),
    ]
