# Generated by Django 5.1.4 on 2025-03-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0024_remove_responsableobra_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsableobra',
            name='responsable_obra',
        ),
    ]
