# Generated by Django 5.1.4 on 2025-04-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0025_remove_responsableobra_responsable_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialregulacionnomina',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='presenteregulacion',
            name='regulacion',
        ),
        migrations.RemoveField(
            model_name='presenteregulacion',
            name='CUIL',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='art',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='rar',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='rgrl',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='venc_rar',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='venc_rgrl',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='nomina',
            name='fecha_incorporacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='obras', to='DASA.art', verbose_name='ART'),
        ),
        migrations.AddField(
            model_name='obra',
            name='sector',
            field=models.CharField(choices=[('OBRA', 'Obra'), ('AGRO', 'Agro'), ('INDUSTRIA_COMERCIO', 'Industria y comercio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='obra',
            name='nro_de_obra',
            field=models.IntegerField(auto_created=True),
        ),
        migrations.CreateModel(
            name='DocumentoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(auto_created=True)),
                ('fecha_carga', models.DateField(auto_now_add=True, null=True)),
                ('fecha_vencimiento', models.DateField(null=True)),
                ('tipo', models.CharField(choices=[('AVISO_DE_OBRA', 'Aviso de obra - extensión'), ('PROGRAMA', 'Programa de seguridad'), ('MEDICION PAT', 'Medición PAT'), ('MEDICION PULSO', 'Medición pulso'), ('MEDICION RUIDOS', 'Medición de ruidos'), ('MEDICION RUIILUMINACIONDOS', 'Medición de iluminación'), ('ERGONOMIA', 'Ergonomía'), ('PLANO', 'Plano de obra - extensión - demolición'), ('MATAFUEGOS', 'Matafuegos'), ('CAPACITACION_SIMULACRO', 'Capacitación - Simulacros'), ('EPP', 'Epp'), ('BALANCIN', 'Balancin'), ('ESTABILIDAD DE SUELOS', 'Estabilidad de suelos'), ('INFORME_TECNICO', 'Informe técnico'), ('AUTO_ELEVADOR', 'Auto-elevador'), ('MATERIAL_PARTICULADO', 'Medición de material particulado'), ('HOJAS_SEGURIDAD', 'Hojas de seguridad'), ('EVACUACION', 'Plano de evacuación'), ('HABITABILIDAD', 'Informe de habitabilidad'), ('MAQUINARIAS', 'Maquinarias'), ('RGRL', 'RGRL'), ('RAR', 'RAR')], max_length=30)),
                ('doc', models.FileField(null=True, upload_to='documentos/', verbose_name='Documento')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='DASA.obra')),
            ],
        ),
        migrations.DeleteModel(
            name='HistorialDocumentoObra',
        ),
        migrations.DeleteModel(
            name='HistorialRegulacionNomina',
        ),
        migrations.DeleteModel(
            name='PresenteRegulacion',
        ),
    ]
