# Generated by Django 5.1.4 on 2025-04-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0026_remove_historialregulacionnomina_obra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='nro_de_obra',
        ),
    ]
