# Generated by Django 5.1.4 on 2025-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0027_remove_obra_nro_de_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoobra',
            name='tipo',
            field=models.CharField(choices=[('AVISO_DE_OBRA', 'Aviso de obra - extensión'), ('PROGRAMA', 'Programa de seguridad'), ('MEDICION_PAT', 'Medición PAT'), ('MEDICION_PULSO', 'Medición pulso'), ('MEDICION_RUIDOS', 'Medición de ruidos'), ('MEDICION ILUMINACION', 'Medición de iluminación'), ('ERGONOMIA', 'Ergonomía'), ('PLANO', 'Plano de obra - extensión - demolición'), ('MATAFUEGOS', 'Matafuegos'), ('CAPACITACION', 'Capacitación'), ('SIMULACRO', 'Simulacro'), ('EPP', 'Epp'), ('BALANCIN', 'Balancin'), ('EST_DE SUELOS', 'Est. de suelos'), ('INFORME_TECNICO', 'Informe técnico'), ('AUTO_ELEVADOR', 'Auto-elevador'), ('MATERIAL_PARTICULADO', 'Medición de material particulado'), ('HOJAS_SEGURIDAD', 'Hojas de seguridad'), ('EVACUACION', 'Plano de evacuación'), ('HABITABILIDAD', 'Informe de habitabilidad'), ('MAQUINARIAS', 'Maquinarias'), ('RGRL', 'RGRL'), ('RAR', 'RAR')], max_length=30),
        ),
        migrations.AlterField(
            model_name='obra',
            name='sector',
            field=models.CharField(choices=[('CONSTRUCCION', 'Construcción'), ('AGRO', 'Agro'), ('INDUSTRIA_COMERCIO', 'Industria y comercio')], max_length=20, null=True),
        ),
    ]
