# Generated by Django 5.1.4 on 2025-04-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0028_alter_documentoobra_tipo_alter_obra_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectoseguridad',
            name='ci',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='aspectoseguridad',
            name='cs',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='documentoobra',
            name='tipo',
            field=models.CharField(choices=[('AVISO_DE_OBRA', 'Aviso de obra - extensión'), ('PROGRAMA', 'Programa de seguridad'), ('MEDICION_PAT', 'Medición PAT'), ('MEDICION_PULSO', 'Medición pulso'), ('MEDICION_RUIDOS', 'Medición de ruidos'), ('MEDICION_ILUMINACION', 'Medición de iluminación'), ('ERGONOMIA', 'Ergonomía'), ('PLANO', 'Plano de obra - extensión - demolición'), ('MATAFUEGOS', 'Matafuegos'), ('CAPACITACION', 'Capacitación'), ('SIMULACRO', 'Simulacro'), ('EPP', 'Epp'), ('BALANCIN', 'Balancin'), ('EST_DE SUELOS', 'Est. de suelos'), ('INFORME_TECNICO', 'Informe técnico'), ('AUTO_ELEVADOR', 'Auto-elevador'), ('MATERIAL_PARTICULADO', 'Medición de material particulado'), ('HOJAS_SEGURIDAD', 'Hojas de seguridad'), ('EVACUACION', 'Plano de evacuación'), ('HABITABILIDAD', 'Informe de habitabilidad'), ('MAQUINARIAS', 'Maquinarias'), ('RGRL', 'RGRL'), ('RAR', 'RAR')], max_length=30),
        ),
        migrations.CreateModel(
            name='HistorialPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='historiales/')),
                ('fecha', models.DateTimeField()),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_planillas', to='DASA.obra')),
            ],
        ),
    ]
