# Generated by Django 5.1.4 on 2025-04-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0029_alter_aspectoseguridad_ci_alter_aspectoseguridad_cs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectoseguridad',
            name='ci',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aspectoseguridad',
            name='cs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
