# Generated by Django 5.1.4 on 2025-04-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0030_alter_aspectoseguridad_ci_alter_aspectoseguridad_cs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialplanilla',
            name='fecha',
            field=models.DateField(),
        ),
    ]
