# Generated by Django 5.1.4 on 2025-04-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0031_alter_historialplanilla_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='fecha_incorporacion',
            field=models.DateField(null=True),
        ),
    ]
