# Generated by Django 5.1.4 on 2025-04-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0033_remove_nomina_id_alter_nomina_cuil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='razon_social',
        ),
    ]
