# Generated by Django 5.1.4 on 2025-04-15 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0034_remove_empresa_email_remove_empresa_razon_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsableobra',
            name='id',
        ),
        migrations.AlterField(
            model_name='responsableobra',
            name='CUIL',
            field=models.CharField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Formato de CUIL incorrecto.', regex='[0-9]{11}$')]),
        ),
    ]
