# Generated by Django 5.1.4 on 2025-04-15 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0036_remove_planilla_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras', to='DASA.art', verbose_name='ART'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='firma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras', to='DASA.responsableobra'),
        ),
    ]
