# Generated by Django 5.1.4 on 2025-04-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0037_alter_obra_art_alter_obra_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='hecha_por',
        ),
        migrations.AddField(
            model_name='planilla',
            name='responsable_obra',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='fecha',
            field=models.DateField(),
        ),
    ]
