# Generated by Django 5.1.4 on 2025-04-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0038_remove_planilla_hecha_por_planilla_responsable_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
