# Generated by Django 5.1.4 on 2025-04-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASA', '0040_alter_aspectoseguridad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='completa',
            field=models.BooleanField(default=False),
        ),
    ]
